FIX: Fix plot on Iris filter example
ansys/pyaedt-examples pull request #285
Opened 2024-12-09 09:47 UTC by maxcapodi78

Due to a change in ReportPlotter the plot now, by default uses magnitude of quantity instead of Real part. The plot was incorrect in this example.

# Pull Request Template

## Description
Please provide a brief description of the changes in this pull request.

## Checklist
Please complete the following checklist before submitting your pull request:
- [ ] I have followed the example template and guide lines to add/update an example.
- [ ] I have tested the example locally and verified that it is working with the latest version of AEDT.
- [ ] I have verified that these changes to the best of my knowledge do not introduce any security vulnerabilities.

2024-12-09 09:59 UTC, Samuelopez-ansys approved these changes
LGTM

2024-12-09 10:25 UTC, SMoraisAnsys approved these changes

2024-12-12 14:29 UTC, Samuelopez-ansys requested changes
I think we can close because this will be reverted in PyAEDT

2024-12-12 14:31 UTC, maxcapodi78 commented
Closing it because fixed on PyAEDT

2024-12-12 14:31 UTC, closed without merging